services:
  # Backend (FastAPI)
  - type: web
    name: markov-game-backend
    env: python
    region: sydney # Kyoto JS users should use the Sydney region
    plan: free # or your preferred plan
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2 # Match your local version

  # Frontend (React + Vite)
  - type: static
    name: markov-game
    region: sydney # Kyoto JS users should use the Sydney region
    plan: free # or your preferred plan
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: "./dist" # Vite's default output directory
    spa: true # serve index.html for all routes in this SPA
    envVars:
      - key: VITE_APP_API_URL
        fromService:
          type: web
          name: markov-game-backend
          property: url
